// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ishankochar09/go_pro/gofrTutorial/service (interfaces: VehicleInterface)

// Package service is a generated GoMock package.
package service

import (
	gofr "developer.zopsmart.com/go/gofr/pkg/gofr"
	gomock "github.com/golang/mock/gomock"
	models "github.com/ishankochar09/go_pro/gofrTutorial/internal/models"
	reflect "reflect"
)

// MockVehicleInterface is a mock of VehicleInterface interface
type MockVehicleInterface struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleInterfaceMockRecorder
}

// MockVehicleInterfaceMockRecorder is the mock recorder for MockVehicleInterface
type MockVehicleInterfaceMockRecorder struct {
	mock *MockVehicleInterface
}

// NewMockVehicleInterface creates a new mock instance
func NewMockVehicleInterface(ctrl *gomock.Controller) *MockVehicleInterface {
	mock := &MockVehicleInterface{ctrl: ctrl}
	mock.recorder = &MockVehicleInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockVehicleInterface) EXPECT() *MockVehicleInterfaceMockRecorder {
	return m.recorder
}

// AllVehicles mocks base method
func (m *MockVehicleInterface) AllVehicles(arg0 *gofr.Context) ([]models.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllVehicles", arg0)
	ret0, _ := ret[0].([]models.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllVehicles indicates an expected call of AllVehicles
func (mr *MockVehicleInterfaceMockRecorder) AllVehicles(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllVehicles", reflect.TypeOf((*MockVehicleInterface)(nil).AllVehicles), arg0)
}

// Create mocks base method
func (m *MockVehicleInterface) Create(arg0 *gofr.Context, arg1 *models.Vehicle) (models.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(models.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockVehicleInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVehicleInterface)(nil).Create), arg0, arg1)
}

// DeleteIDVehicle mocks base method
func (m *MockVehicleInterface) DeleteIDVehicle(arg0 *gofr.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIDVehicle", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIDVehicle indicates an expected call of DeleteIDVehicle
func (mr *MockVehicleInterfaceMockRecorder) DeleteIDVehicle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIDVehicle", reflect.TypeOf((*MockVehicleInterface)(nil).DeleteIDVehicle), arg0, arg1)
}

// GetIDVehicle mocks base method
func (m *MockVehicleInterface) GetIDVehicle(arg0 *gofr.Context, arg1 int) (models.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDVehicle", arg0, arg1)
	ret0, _ := ret[0].(models.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDVehicle indicates an expected call of GetIDVehicle
func (mr *MockVehicleInterfaceMockRecorder) GetIDVehicle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDVehicle", reflect.TypeOf((*MockVehicleInterface)(nil).GetIDVehicle), arg0, arg1)
}

// UpdateIDVehicle mocks base method
func (m *MockVehicleInterface) UpdateIDVehicle(arg0 *gofr.Context, arg1 int, arg2 *models.Vehicle) (models.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIDVehicle", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIDVehicle indicates an expected call of UpdateIDVehicle
func (mr *MockVehicleInterfaceMockRecorder) UpdateIDVehicle(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIDVehicle", reflect.TypeOf((*MockVehicleInterface)(nil).UpdateIDVehicle), arg0, arg1, arg2)
}
